# Generated by Django 3.1.1 on 2020-10-03 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', isbn_field.fields.ISBNField(max_length=28, primary_key=True, serialize=False, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('name', models.CharField(max_length=255)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Expired'), (2, 'Returned')], default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
